### PR TITLE
Material UI - Workspace

### PR DESCRIPTION
**Pull request by cabarnes**
Convert workspace to Material UI

### CODE REVIEW

**Comment by aninternetof** [comment]
You go the control buttons in front of the workspace! Awesome!

**Comment by aninternetof** [comment]
I'm seeing some odd resizing behavior. As I drag to make my browser wider, the workspace seems to get taller and taller.
I know the resizing stuff is a nightmare, so we can punt on this until later if you'd rather.

**Comment by cabarnes** [comment]
@aninternetof I saw the same thing so I set the max height. It looked fine on my screen but maybe we need to make it a smaller value

**Comment by aninternetof** [comment]
It seems to always calculate correctly on page refresh, so I'm fine leaving it for later tweaking/investigation/experimentation.

**Pull request merged**
