### PR TITLE
Rover credentials

### PR DESCRIPTION
**Pull request by cabarnes**
Adds a download link for the rover credentials on the details page. When a rover is created and the user is re-directed to this page, a message is displayed at the top to notify the user of how to download the credentials:
image
When the `Download Credentials` button is pressed, a modal pops up to enter the WiFi credentials:
image
Clicking `Download` initiates the download of the `.env` file

### CODE REVIEW

**Comment by cabarnes** [comment]
@aninternetof Here it is with the message displayed:
image
Here it is without:
image

**Comment by aninternetof** [comment]
I kinda like it with the message. It might be overkill, but might as well err on the side of overly explicit?

**Comment by cabarnes** [comment]
It only shows the message when you first create the rover. The second image is when you click on `Configure` from the rover list

**Comment by aninternetof** [comment]
Oh, I see! That's perfect.

**Comment by cabarnes** [comment]
Example `.env` file download:

`rovercode_Rover 3.env `
```
CLIENT_ID=7T69fPYWNJdxx6vcf9uNC99VaehCgEd9sbO8k9vS
CLIENT_SECRET=HDOEWDASjqLTiazlGFCJqWu9QUeAyE8gu5iby0XyUVRelqeamGUsYYGkG1pd6kAQ6ag53BLefjj3l3xPNeGVjNx1xVDh7sylsmWKXmbqiirG7QBiWcVv1U1sYktMVyxn
AP_NAME=apname
AP_PASSWORD=appassword
```

**Comment by aninternetof** [comment]
Oh, nevermind -- I see the labels in the form defaults. That's good for me.

**Pull request merged**
