### PR TITLE
Programs pagination

### PR DESCRIPTION
**Pull request by cabarnes**
A part of #18 

Implements pagination for the programs list. If this all looks good, I'll do the same for the rover list.
image

### CODE REVIEW

**Comment by aninternetof** [comment]
When I have only one page of content, I'm seeing something interesting:

image

The console shows a React list key warning:
```
index.js:3757 Warning: Encountered two children with the same key, `ellipsisItem-NaN`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

Any idea what's up? I'll keep debugging it, too.

**Comment by cabarnes** [comment]
I was thinking that it might make sense to just remove the pagination when there is only one page. None of the buttons would do anything and it might be confusing to the user. What do you think?

**Comment by aninternetof** [comment]
I think that's a great idea.

**Comment by cabarnes** [comment]
Implemented it that way. I definitely like it.

**Pull request merged**
