### PR TITLE
Internationalization

### LINKED ISSUE #11: Add localization
Maybe using this method: https://medium.com/@ryandrewjohnson/adding-multi-language-support-to-your-react-redux-app-cf6e64250050

### PR DESCRIPTION
**Pull request by cabarnes**
Closes #11 

Uses [react-intl](https://github.com/formatjs/react-intl) to add internationalization to the UI. Right now, it is setup to output English and Spanish strings. The Spanish file just has the extracted English strings until it can be updated for Spanish.
When new strings are added, `yarn run i18n:manage` will update the strings in the locale files. The entire list of strings with descriptions is output to `src/translations/locales/defaultMessages.json`. On `yarn start` or on save of a file while running, babel outputs the extracted strings to `src/translations/extracted/`.

### CODE REVIEW

**Comment by aninternetof** [comment]
I like how this is set up.

Is the next step to have a toggle or dropdown to switch them on the fly? Or is that already there and I'm missing it?

**Comment by cabarnes** [comment]
Right now, it's based on the language selected by the browser.
For instance, in Chrome:
image

**Comment by aninternetof** [comment]
Oh nice!

I wonder if most student know to set that in their browser? This is where some market research could help. I can ask some teacher friends.

How tricky would it be to have a picker in our UI that could override the Chrome default?

**Comment by cabarnes** [comment]
I don't think that would be too difficult, but I think due to the size of this PR, I would prefer to do that as a separate task

**Comment by aninternetof** [comment]
Now I'm having doubts about the on-screen picker. Why not let the browser manage their preference.

Maybe we could put a note on the user settings page, with a link to instructions on how to set the default language in various browsers? The only challenge there is finding an instructions link that is permanent enough.

**Comment by cabarnes** [comment]
It seems like a language picker might be easier to support. Different browsers will have different instructions and they will change over time

**Comment by aninternetof** [comment]
Yeah, that's true.

That makes we wonder if we should support saving their preference on their user model, though :-/

**Comment by cabarnes** [comment]
We could definitely do that. It would just be one field to add

**Comment by aninternetof** [comment]
Cool, let's do that. It doesn't matter to me if we do that now or in its own PR, so I'll approve this one.

**Pull request merged**
