### PR TITLE
Blockly integration

### PR DESCRIPTION
**Pull request by cabarnes**
A start of #20 
This integrates blockly with custom blocks into the application. A workspace component has been created with a redux store of the generated code from the blocks. Currently, that code is just displayed but will eventually be in a code viewer like the previous UI.
Both [blockly](https://github.com/rovercode/blockly/tree/custom-blocks) and [node-blockly]( https://github.com/rovercode/node-blockly/tree/custom-blockly) were forked for the custom blocks to import correctly.
image

### CODE REVIEW

**Comment by aninternetof** [comment]
I'm getting the failure below on `yarn install`. Looks like a failure building the libxmljs, a native module.

@jakenewby or @galitskyd, do you see anything like this?

Same failure for node version 10.4.1 and 10.9.0.[ I suspect it's a some sort of C build tool I'm missing](https://github.com/libxmljs/libxmljs/issues/406).

```
xmljs.target.mk:109: recipe for target 'Release/obj.target/xmljs/src/libxmljs.o' failed
make: Leaving directory '/home/bradyhurlburt/rovercode-ui/node_modules/libxmljs/build'
make: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.13.0-46-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/bradyhurlburt/rovercode-ui/node_modules/libxmljs
gyp ERR! node -v v10.4.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Comment by galitskyd** [comment]
I'll have to take a look at this more tomorrow.

**Comment by cabarnes** [comment]
Sorry, totally forgot to put that in the description. You have to use the LTS version of node which is what we use in Travis CI. Version 10.x fails with that library error.

**Comment by cabarnes** [comment]
If I remember the rabbit hole correctly, I think it's related to [node-blockly](https://github.com/mo4islona/node-blockly/blob/master/package.json#L15) requiring [xmlshim](https://github.com/znerol/node-xmlshim/blob/2.x/package.json#L31) requiring a forked version of `libxmljs` which is probably why it works differently by itself for you using the main repository.

**Comment by aninternetof** [comment]
Awesome! I'll try it with v8.11.4 tonight! (let's hear it for `n`).

**Pull request merged**
