### PR TITLE
Program list

### PR DESCRIPTION
**Pull request by cabarnes**
First part of #18 

Displays all of the programs with an `Edit` button that loads the program in mission control. Right now displays the user ID since that's what the API provides. This is also now the landing page after logging in.

image
Some changes needed from the API:
* Username of the owner
* Date/Time
* Pagination

### CODE REVIEW

**Comment by aninternetof** [comment]
This looks great!

I'll get on those API changes, and we can handle the corresponding UI updates in a new PR.

I had a couple new ideas which might make the program card component reuseable for both the "My Programs" view and the "Explore" view.

- Could the text of "Edit" button be a local component parameter? It could read "View" on the Explore view, and "Keep working" on the My Programs view.
- Could there be a component parameter to show/hide the user name/id? It could be hidden on the My Programs view.

What do you think?

**Comment by cabarnes** [comment]
I was thinking about the `Explore` and `My Programs` concept. Since both pages are going to be a grouping of cards, should they just be on the same page? Should the concept of the user's programs just be a filter? We're going to use the same search and card layout. The button text can change based on the owner. The owner name could even change to `Mine` or something instead of the username

**Comment by aninternetof** [comment]
I like it! Let's combine them in one page.

On that page, what if there one group of cards that was pre-filtered to be only that user's programs. Then below, a group of cards pre-filtered to be *not* that user's programs. Other filters (like lesson-plan tags when we have them) could be applied to both groups.

Alternatively, it could just be one big filterable group. But, wanting to see your own programs seems like such a common task that it might be nice to have a pre-filtered group for that.

**Comment by aninternetof** [comment]
We could also make that programs page the `/` route, too.

**Comment by cabarnes** [comment]
This PR makes this page `/` (in `src/index.js`)

**Comment by aninternetof** [comment]
Perfect -- sorry, I missed that.

**Comment by cabarnes** [comment]
@aninternetof There are now two groups of programs:
* The current user's programs:
image
* Other user's programs (currently the API doesn't have an `exclude` parameter so it's just all the programs):
image

The state now has both lists. So, each group can be filtered and sorted differently. We would need to add those controls to each group as well as pagination

**Pull request merged**
