### PR TITLE
Remix programs

### LINKED ISSUE #64: Support program remixing
## Option 1
If a student is viewing someone else's program in mission control, it is read-only (I think there's a flag we can set on the Blockly workspace that disables the blocks from even moving).
Within Mission Control, there is a "Remix this Program!" button, which copies the program to the users' account, and makes it editable.
***Pro***: The user can view someone else's program without copying it into her account.
***Con***: It might not be clear to the user why a program is read-only, and it may appear like Mission Control is frozen when the blocks don't move.

## Option 2
From the program list view, every program that does not belong to the user has a "Remix" button instead of the "View" button. When the user clicks the remix button, the program is copied into her account and she is immediately taken to Mission Control where she can edit it.
***Pro***: If the user can see a program, it is hers and she can edit it. Never are the blocks frozen.
***Con***: The user's program list will become cluttered with programs she just wanted to view.

*Note*: Scratch and Glitch both use Option 1.

------------------------

@cabarnes, it's possible that remixing could be a UI-only ticket, since the UI has the ability fetch and create new programs. Or, can you think of a specialized API endpoint that would make this easier on the UI?

### PR DESCRIPTION
**Pull request by cabarnes**
Closes #64 

Depends somewhat on https://github.com/rovercode/rovercode-web/pull/239 for name conflict resolution.

Adds a `Remix` button when viewing a program in read-only mode:
image
When clicked, the program is copied for the current user. The user is redirected back to the programs list with a message indicating that the remix is complete:
image
The user can now edit the program like any other owned program.

This seemed like the safest way to handle all of the state change through mission control when a new program is loaded and is now writable.

### CODE REVIEW

**Comment by aninternetof** [comment]
> The user is redirected back to the programs list... This seemed like the safest way to handle all of the state change through mission control when a new program is loaded and is now writable.

It sounds like you tried it and it got pretty complicated, but would it be possible to keep the user in Mission Control and replace the program with their new, editable one? Scratch and Glitch do that, and it's really nice to go straight from viewing someone else's to editing your own copy.

If it's way too hairy, we can punt on it.

**Comment by cabarnes** [comment]
It did get complicated so I wanted to get your thoughts on this approach. One idea that I had was to just have the program list immediately load the new program and redirect the user back to mission control. I can try that and see what the user experiences.

**Comment by cabarnes** [comment]
@aninternetof I figured out the right way to accomplish this with leaving the user in Mission Control. The read only state was moved to redux so that the workspace and program name components can render on a change. The Blockly workspace must be removed and re-created to change the read only state: https://groups.google.com/forum/#!topic/blockly/NCukwTKMR0U

**Comment by aninternetof** [comment]
Hm. I created two users. Every program I create for user `hbradio` also shows up as a program owned by the other user `otheruser`.

image

This could be another symptom of the state not clearing when I log out?

**Comment by aninternetof** [comment]
I narrowed my problem down to the API ignoring my query filters on my local machine. I don't see the same problem in alpha, and it has nothing to do with the UI, so I think we're good to merge this!

**Pull request merged**
